version: '3.8'

services:
  svelte-frontend:
    build:
      context: ./svelte-app
      dockerfile: Dockerfile
    container_name: svelte-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - pocketbase