# Configuración de Nixpacks para Railway

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'npm install --include=optional'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'node build'

[variables]
NODE_ENV = 'production'
HOST = '0.0.0.0'